
export const nth = new Map<number, string>([
    [1, "first"],
    [2, "second"],
    [3, "third"],
    [4, "fourth"],
    [5, "fifth"],
    [6, "sixth"],
    [7, "seventh"],
    [8, "eighth"],
    [9, "ninth"],
    [10, "tenth"],
    [11, "eleventh"],
    [12, "twelfth"],
    [13, "thirteenth"],
    [14, "fourteenth"],
    [15, "fifteenth"],
    [16, "sixteenth"],
    [17, "seventeenth"],
    [18, "eighteenth"],
    [19, "nineteenth"],
    [20, "twentieth"],
    [21, "twenty-first"],
    [22, "twenty-second"],
    [23, "twenty-third"],
    [24, "twenty-fourth"],
    [25, "twenty-fifth"],
    [26, "twenty-sixth"],
    [27, "twenty-seventh"],
    [28, "twenty-eighth"],
    [29, "twenty-ninth"],
    [30, "thirtieth"],
    [31, "thirty-first"],
    [32, "thirty-second"],
    [33, "thirty-third"],
    [34, "thirty-fourth"],
    [35, "thirty-fifth"],
    [36, "thirty-sixth"],
    [37, "thirty-seventh"],
    [38, "thirty-eighth"],
    [39, "thirty-ninth"],
    [40, "fortieth"],
    // Yes, I do not expect King Charles III to stay in power for more than 40 years.
    // Neither do I expect this website to be around for that long.
]);

export const months = new Map<number, string>([
    [1, "January"],
    [2, "February"],
    [3, "March"],
    [4, "April"],
    [5, "May"],
    [6, "June"],
    [7, "July"],
    [8, "August"],
    [9, "September"],
    [10, "October"],
    [11, "November"],
    [12, "December"],
]);

export const years = new Map<number, string>([
    [2022, "two thousand and twenty-two"],
    [2023, "two thousand and twenty-three"],
    [2024, "two thousand and twenty-four"],
    [2025, "two thousand and twenty-five"],
    [2026, "two thousand and twenty-six"],
    [2027, "two thousand and twenty-seven"],
    [2028, "two thousand and twenty-eight"],
    [2029, "two thousand and twenty-nine"],
    [2030, "two thousand and thirty"],
    [2031, "two thousand and thirty-one"],
    [2032, "two thousand and thirty-two"],
    [2033, "two thousand and thirty-three"],
    [2034, "two thousand and thirty-four"],
    [2035, "two thousand and thirty-five"],
    [2036, "two thousand and thirty-six"],
    [2037, "two thousand and thirty-seven"],
    [2038, "two thousand and thirty-eight"],
    [2039, "two thousand and thirty-nine"],
    [2040, "two thousand and forty"],
    [2041, "two thousand and forty-one"],
    [2042, "two thousand and forty-two"],
    [2043, "two thousand and forty-three"],
    [2044, "two thousand and forty-four"],
    [2045, "two thousand and forty-five"],
    [2046, "two thousand and forty-six"],
    [2047, "two thousand and forty-seven"],
    [2048, "two thousand and forty-eight"],
    [2049, "two thousand and forty-nine"],
    [2050, "two thousand and fifty"],
    [2051, "two thousand and fifty-one"],
    [2052, "two thousand and fifty-two"],
    [2053, "two thousand and fifty-three"],
    [2054, "two thousand and fifty-four"],
    [2055, "two thousand and fifty-five"],
    [2056, "two thousand and fifty-six"],
    [2057, "two thousand and fifty-seven"],
    [2058, "two thousand and fifty-eight"],
    [2059, "two thousand and fifty-nine"],
    [2060, "two thousand and sixty"],
    [2061, "two thousand and sixty-one"],
    [2062, "two thousand and sixty-two"],
    [2063, "two thousand and sixty-three"],
    [2064, "two thousand and sixty-four"],
    [2065, "two thousand and sixty-five"],
    [2066, "two thousand and sixty-six"],
    [2067, "two thousand and sixty-seven"],
    [2068, "two thousand and sixty-eight"],
    [2069, "two thousand and sixty-nine"],
    [2070, "two thousand and seventy"],
    [2071, "two thousand and seventy-one"],
    [2072, "two thousand and seventy-two"],
    [2073, "two thousand and seventy-three"],
    [2074, "two thousand and seventy-four"],
    [2075, "two thousand and seventy-five"],
    [2076, "two thousand and seventy-six"],
    [2077, "two thousand and seventy-seven"],
    [2078, "two thousand and seventy-eight"],
    [2079, "two thousand and seventy-nine"],
    [2080, "two thousand and eighty"],
    [2081, "two thousand and eighty-one"],
    [2082, "two thousand and eighty-two"],
    [2083, "two thousand and eighty-three"],
    [2084, "two thousand and eighty-four"],
    [2085, "two thousand and eighty-five"],
    [2086, "two thousand and eighty-six"],
    [2087, "two thousand and eighty-seven"],
    [2088, "two thousand and eighty-eight"],
    [2089, "two thousand and eighty-nine"],
    [2090, "two thousand and ninety"],
    [2091, "two thousand and ninety-one"],
    [2092, "two thousand and ninety-two"],
    [2093, "two thousand and ninety-three"],
    [2094, "two thousand and ninety-four"],
    [2095, "two thousand and ninety-five"],
    [2096, "two thousand and ninety-six"],
    [2097, "two thousand and ninety-seven"],
    [2098, "two thousand and ninety-eight"],
    [2099, "two thousand and ninety-nine"],
    [2100, "two thousand and one hundred"],
    // That should be enough, thanks Copilot!
]);